version: "3.9"
services:
  backend:
    build: ./IMS/backend
    container_name: ims-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=${MONGO_URI}        # read from .env file
      - SECRET=${SECRET}              # JWT secret from .env file
    volumes:
      - ./IMS/backend:/usr/src/app    # hot-reload in dev mode
      - /usr/src/app/node_modules     # anonymous volume for node_modules
    command: ["node", "server.js"]
    restart: unless-stopped

  frontend:
    build: ./IMS/frontend
    container_name: ims-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:5000  # frontend points to backend
    volumes:
      - ./IMS/frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"]
    restart: unless-stopped
