name: IMS Backend CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "IMS/backend/**" # run only if backend changes

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push backend Docker image
        run: |
          docker build IMS/backend \
            -t alikhandevs/ims-backend:latest \
            -t alikhandevs/ims-backend:${{ steps.vars.outputs.sha_short }}
          docker push alikhandevs/ims-backend:latest
          docker push alikhandevs/ims-backend:${{ steps.vars.outputs.sha_short }}

      - name: Trigger Render backend deploy
        run: |
          curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK }}
